services:
  backend:
    build:
      context: .
      target: dev
    image: kvdomingo/ncovenience-api:latest
    init: true
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/backend
    ports:
      - "8000:8000"

  frontend:
    image: oven/bun:1.1-alpine
    init: true
    restart: unless-stopped
    environment:
      NODE_ENV: development
    env_file: .env
    entrypoint:
      - /bin/sh
      - -c
      - bun install && exec bun run dev
    working_dir: /web
    volumes:
      - ./ui:/web
    ports:
      - "3000:3000"
