version: '3'

env:
  NAME: ncovenience-dev
  VERSION:
    sh: git show --format="%aI %h" --no-patch

dotenv:
  - .env

tasks:
  default:
    desc: Build and start containers
    cmds:
      - docker compose -p $NAME up -d --build --remove-orphans {{.CLI_ARGS}}
      - task logs

  reload-proxy:
    desc: Reload proxy config
    cmds:
      - docker compose -p $NAME exec -- proxy nginx -s reload

  exec:
    desc: Execute command in specified container
    cmds:
      - docker compose -p $NAME exec -- {{.CLI_ARGS}}

  restart:
    desc: Restart all containers
    cmds:
      - docker compose -p $NAME restart {{.CLI_ARGS}}

  logs:
    desc: Show Docker logs
    cmds:
      - docker compose -p $NAME logs --follow {{.CLI_ARGS}}

  shutdown:
    desc: Stop all containers
    cmds:
      - docker compose -p $NAME stop {{.CLI_ARGS}}

  clean:
    desc: Stop and remove all containers
    cmds:
      - docker compose -p $NAME down -v --remove-orphans
